spring.application.name=identity-service
server.port=8085

# Eureka client configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance-id:${random.value}}

# JWT Configuration
app.jwt-secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
# Token expiration time in milliseconds - 1 day
app.jwt-expiration-ms=86400000