DROP DATABASE IF EXISTS user_db;
DROP DATABASE IF EXISTS quiz_db;
DROP DATABASE IF EXISTS question_db;
DROP DATABASE IF EXISTS gameplay_db;


CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS quiz_db;
CREATE DATABASE IF NOT EXISTS question_db;
CREATE DATABASE IF NOT EXISTS gameplay_db;
